### ISSUE TITLE
Requested features

### ISSUE THREAD

**Issue by akshaygpt** [cloudmesh/cloudmesh-javascript#14]
- [x] make the layout of title and buttons similar to old design
- [x] reduce padding
- [x] take cloud providers out of sidebar
- [x] mini card view
- [x] make table view default
- [x] Style Sidebar with material ui
- [x] Profile button in sidebar
- [x] Add tooltips for icons

**Comment by laszewsk** [comment]
I have unchecked 

`reduce padding`

as it does not work in the branch that it was committed to.(develop)

Neither `yarn dev` nor more importantly `cms viewer start dev` work

**Comment by akshaygpt** [comment]
Reopening because 2 tasks out of these are under development.
