### ISSUE TITLE
develop branch does not work

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-javascript#17]
$ yarn run format
$ prettier --write *.{js,css}
jest.config.js 46ms
$ nextron
[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:8888 ...
[ error ] ../node_modules/next/dist/client/dev/amp-dev.js
Error: [BABEL] /Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-javascript/node_modules/next/dist/client/dev/amp-dev.js: Cannot find module '@babel/helper-validator-identifier' (While processing: "programmatic item")
[ wait ]  compiling ...
[ error ] ../node_modules/next/dist/client/dev/amp-dev.js
Error: [BABEL] /Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-javascript/node_modules/next/dist/client/dev/amp-dev.js: Cannot find module '@babel/helper-validator-identifier' (While processing: "programmatic item")
[ wait ]  compiling ...
[ error ] ../node_modules/next/dist/client/dev/amp-dev.js
Error: [BABEL] /Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-javascript/node_modules/next/dist/client/dev/amp-dev.js: Cannot find module '@babel/helper-validator-identifier' (While processing: "programmatic item")
[ wait ]  compiling ...
[ error ] ../node_modules/next/dist/client/dev/amp-dev.js
Error: [BABEL] /Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-javascript/node_modules/next/dist/client/dev/amp-dev.js: Cannot find module '@babel/helper-validator-identifier' (While processing: "programmatic item")
[ wait ]  compiling ...
[ error ] ../node_modules/next/dist/client/dev/amp-dev.js
Error: [BABEL] /Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-javascript/node_modules/next/dist/client/dev/amp-dev.js: Cannot find module '@babel/helper-validator-identifier' (While processing: "programmatic item")

**Comment by jogoodma** [comment]
Should be working now.
