### ISSUE TITLE
develop: errors

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-javascript#18]
yarn build
please make sure also

cms viewer start dev 

works

Cannot build electron packages:
Error: ENOENT: no such file or directory, stat '/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-javascript/renderer/out'

**Comment by akshaygpt** [comment]
Have you activated `ENV3`? `Error: ENOENT: no such file or directory, stat '/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-javascript/renderer/out'` happens when we're trying to run without activating `ENV3`.

**Comment by laszewsk** [comment]
my env 3 is always active

**Comment by jogoodma** [comment]
Based on our meeting last Friday I believe that this is now resolved.
